services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "2751:8000"
    entrypoint: /app/entrypoint.sh
    command: gunicorn timesheet.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./data:/app/data
      - static_files:/app/staticfiles
    restart: unless-stopped

volumes:
  static_files:
