services:
  web:
    build: .
    ports:
      - "2751:8000"
    command: gunicorn datasheet.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - db_data:/app/data
    restart: unless-stopped

volumes:
  db_data:
