# Generated by Django 5.2.3 on 2025-07-02 10:00

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now)),
                ('end_time', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='timer.task')),
            ],
        ),
    ]
