# Generated by Django 5.2.3 on 2025-07-04 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), editable=False),
        ),
    ]
