# Generated by Django 5.2.3 on 2025-07-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_project_total_duration_task_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='description',
        ),
    ]
